#define CBF_O_TILE_WIDTH 12
#define CBF_MASK_WIDTH 5
#define CBF_I_TILE_WIDTH (CBF_O_TILE_WIDTH + CBF_MASK_WIDTH -1)

#define FILTER_MODE_CROSS 2
#define FILTER_MODE_BILATERAL 1
#define FILTER_MODE_UNILATERAL 0

#define MAX_TEMPORAL_FREQ_FILT_SAMPLES 10
#define TEMPORAL_FREQ_FILT_MODE_0 0
#define TEMPORAL_FREQ_FILT_MODE_1 1
#define TEMPORAL_FREQ_FILT_MODE_2 2
#define TEMPORAL_FREQ_FILT_MODE_3 3
#define TEMPORAL_FREQ_FILT_MODE_4 4
#define TEMPORAL_FREQ_FILT_MODE_5 5